In [ ]:
import os

In [ ]:
os.getcwd()

'/content'

In [ ]:
import numpy as npd

In [ ]:
data_srd = {i : np.random.randn() for i in range(100)}

In [ ]:
data_srd

In [ ]:
type(data)

dict

In [ ]:
data_srd2 =  {i : np.random. randn(1,3) for i in range(10)}


In [ ]:
data_srd2

In [ ]:
b =[1,2,3]

In [ ]:
b

[1, 2, 3]

In [ ]:
import datetime

In [ ]:
datetime

<module 'datetime' from '/usr/lib/python3.7/datetime.py'>

In [ ]:
def add_numbers(x,y,z=None) :
  return (x+y)
  add_numbers(1,2,)
add_numbers(1,2,)

3

In [ ]:
def add_numbers(x,y,z=None):
  if (z==None):
    return(x+y)
  else:
      return(x+y+z)
  print(add_numbers(1,2,))
  print(add_numbers(1,2,5))


In [ ]:
print(add_numbers(1,2,5))

8


In [ ]:
type(add_numbers)

function

In [ ]:
def f(a,b,c) :
  return(a+b+c)

In [ ]:
a = 2.5
b =3.5
c= 0.23
result = f(a,b,c)
result

6.23

In [ ]:
print(result)

6.23


In [ ]:
!dir c

dir: cannot access 'c': No such file or directory


In [ ]:
a = np.arange(6)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a >=5

array([False, False, False, False, False,  True])

In [ ]:
a <= -1

array([False, False, False, False, False, False])

In [ ]:
a=[a>=8.5]

In [ ]:
a

[array([False, False, False, False, False, False])]

In [ ]:
a = np.arange(5)
a
print(a <= 3)

[ True  True  True  True False]


In [ ]:
a = np.arange(1000)
%time np.sum(a**2)

CPU times: user 266 µs, sys: 39 µs, total: 305 µs
Wall time: 317 µs


332833500

In [ ]:
import pandas as pd
import numpy as np

import math
import matplotlib
matplotlib


<module 'matplotlib' from '/usr/local/lib/python3.7/dist-packages/matplotlib/__init__.py'>

In [ ]:
modeleff = pd.Series([0.23, 0.45,0.06,0.09],index=['creditvar','kmv','logistic','naive bayes'])


In [ ]:
modeleff

creditvar      0.23
kmv            0.45
logistic       0.06
naive bayes    0.09
dtype: float64

In [ ]:
print(modeleff)

creditvar      0.23
kmv            0.45
logistic       0.06
naive bayes    0.09
dtype: float64


In [ ]:
ctf = pd.DataFrame({ 'certificates':[8,2,5,6],'Time in months':[16,5,9,12]})

In [ ]:
import pandas as pd
pd

<module 'pandas' from '/usr/local/lib/python3.7/dist-packages/pandas/__init__.py'>

In [ ]:
ctf

certificates  Time in months
0             8              16
1             2               5
2             5               9
3             6              12

In [ ]:
ctf.index = ['Tom', 'kris', 'Ahmad' , 'Beau']

In [ ]:
ctf.index

Index(['Tom', 'kris', 'Ahmad', 'Beau'], dtype='object')

In [ ]:
ctf

certificates  Time in months
0             8              16
1             2               5
2             5               9
3             6              12

In [ ]:
print =ctf.iloc[2]

In [ ]:
print

certificates      5
Time in months    9
Name: 2, dtype: int64

In [ ]:
my_list = [['p','o'],["human","odds"],[1,2,3,5.6]]

In [ ]:
print(my_list)

[['p', 'o'], ['human', 'odds'], [1, 2, 3, 5.6]]


In [ ]:
my_list = ['p','r','o','g','r','a','m','i','z']
print(my_list[:])


['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


In [ ]:
odd = [3,5,7,9]
print(odd)
odd[2]=11
print(odd)
# the above s changing the elements of a list.

[3, 5, 7, 9]
[3, 5, 11, 9]


In [ ]:
# appending the list
odd.append(19)
odd.extend([13,17,19,21])
print(odd)
# appending and extending the list of odd numbers


[3, 5, 11, 9, 19, 19, 19, 19, 13, 17, 19, 21, 19, 13, 17, 19, 21]


In [ ]:
del my_list[:-2]

In [ ]:
print(my_list)

['i', 'z']


In [ ]:
my_list = ['p','r','o','b','l','e','m']
print(my_list)
my_list.remove('p')
print(my_list)
my_list.pop(4)
print(my_list)
# using remove() and pop() functions to remove a specific item from a list based on index position.

['p', 'r', 'o', 'b', 'l', 'e', 'm']
['r', 'o', 'b', 'l', 'e', 'm']
['r', 'o', 'b', 'l', 'm']


In [ ]:
my_list.insert(3,'human')
print(my_list)

['r', 'o', 'b', 'human', 'human', 'human', 'l', 'm']


In [ ]:
print(my_list)

['r', 'o', 'b', 'human', 'human', 'human', 'l', 'm']


In [ ]:
import math
math

<module 'math' (built-in)>

In [ ]:
st1 = [2**x for x in range(3) ]

In [ ]:
print(st1)    # the range takes sequential successive value of x taking terms 0,1,2,3 ......

[1, 2, 4]


In [ ]:
pow2 = [2 ** x for x in range(10) if x > 6]
print(pow2)

[128, 256, 512]


In [ ]:
my_tuple = {1,2,3,0.78,3.7}
print(my_tuple)

{0.78, 1, 2, 3, 3.7}


In [ ]:
my_set2 = set({1,2,3,4})
print(my_set2)


{1, 2, 3, 4}


In [ ]:
import re

In [ ]:
my_txt = "The spain is your train"

In [ ]:
my_txt

'The spain is your train'

In [ ]:
x = re.search("The spain", my_txt)

In [ ]:
print(x)

<re.Match object; span=(0, 9), match='The spain'>


In [ ]:
my_txt1 = "Regular expressions can be built by metacharacters, and patterns can be processed using a library in Python for Regular Expressions known as re"

In [ ]:
my_txt1

'Regular expressions can be built by metacharacters, and patterns can be processed using a library in Python for Regular Expressions known as re'

In [ ]:
x = re.search([^a-d]:my_txt1) 

SyntaxError: ignored